### ISSUE TITLE
Add sway pattern to openSUSE

### ISSUE THREAD

**Issue by jubalh** [openSUSE/openSUSEway#1]
Hi,

I planned to have a Sway pattern for a long time so users can easily install Sway and get all the tools.
I also planned to have a default theme provided which was mostly the reason I didn't create the pattern yet (because I didn't have a nice theme :-)).

Since I have holidays this week I quickly created the pattern and it is on its way to [Factory](https://build.opensuse.org/request/show/808936) now.

You can create a branding package and add them to the pattern (like done for XFCE etc) and then we have a nice and easy way to get a sway environment for beginners on openSUSE.

Usually we ship two branding packages, upstream and openSUSE. So users can decide whether they want the default configs or the theming provided by us.

This issue is to track the state of the pattern for openSUSE:
- [x] create a basic pattern [patterns-sway](https://build.opensuse.org/package/show/X11:Wayland/patterns-sway)
- [x] create an icon for the installer

**Comment by denisok** [comment]
nice plan :)

> +# spec file for package patterns-lxqt
that is from the old pattern.

For the branding, what to start with ? I am really bad with designs, I can create one with what I have here, but it is not the best one.

Also for the pattern, to start everything automatically I haven't solved sway systemd issue, systemd way doesn't work for me (one that described upstream).
Mako, waybar systemd work fine, and I could add some systemd packages for them. But it doesn't work for the sway for me.

Do we want pattern to include:

* systemd package
* login manager (GDM?)

**Comment by jubalh** [comment]
>  that is from the old pattern.

Saw it too. Fixed it then.

>  I am really bad with designs, I can create one with what I have here, but it is not the best one.

It's a start :)

> login manager (GDM?)

As far as I know launching sway with GDM  or any display manager is not supported.
Drew always discourages that use too. I launch sway like described in the [wiki](https://github.com/swaywm/sway/wiki).

We could also auto launch based on some default config if there are problems with systemd?

**Comment by denisok** [comment]
> > login manager (GDM?)
> 
> As far as I know launching sway with GDM or any display manager is not supported.

There is only this mention:
> Some login managers support Wayland, and others don't. 
GDM supports it just fine. And I have it working for some time now (running sway from wayland-sessions):
https://en.opensuse.org/Sway#GDM

I could add that desktop file to some package.

> Drew always discourages that use too. I launch sway like described in the [wiki](https://github.com/swaywm/sway/wiki).

I didn't know about it.

> 
> We could also auto launch based on some default config if there are problems with systemd?

yes, that is already possible.

**Comment by jubalh** [comment]
I know about the mention in the wiki. However it is still considered unsupported. Regardless that it works with some display managers just fine (right now).

Once the Pattern had landed in Factory. It will be selectable in the Installer too.
Additionally one could create a custom ISO with kiwi.

**Comment by denisok** [comment]
BTW sway package installs desktop file by default:
> [   89s] Installing /home/abuild/rpmbuild/BUILD/sway-1.4/sway.desktop to /home/abuild/rpmbuild/BUILDROOT/sway-1.4-55.1.x86_64/usr/share/wayland-sessions

**Comment by denisok** [comment]
https://github.com/denisok/openSUSEway/issues/2#issuecomment-636029224

**Comment by itaranto** [comment]
> nice plan :)
> 
> > +# spec file for package patterns-lxqt
> > that is from the old pattern.
> 
> For the branding, what to start with ? I am really bad with designs, I can create one with what I have here, but it is not the best one.
> 
> Also for the pattern, to start everything automatically I haven't solved sway systemd issue, systemd way doesn't work for me (one that described upstream).
> Mako, waybar systemd work fine, and I could add some systemd packages for them. But it doesn't work for the sway for me.
> 
> Do we want pattern to include:
> 
>     * systemd package
> 
>     * login manager (GDM?)

I wouldn't use GDM since it pulls the ENTIRE GNOME DESKTOP when installing, even with --no-recommends.

I have some fixes with the waybar and overall sway colors, maybe I will open PR.

**Comment by denisok** [comment]
> > * login manager (GDM?)
> > ```
> 
> I wouldn't use GDM since it pulls the ENTIRE GNOME DESKTOP when installing, even with --no-recommends.

I was surprised about it, you just need to install it correctly :)
I was able to install only minimal gdm dependencies with some tweaks. I need to recall what, but it is possible to avoid patterns-gnome-*

> 
> I tried both with SDDM and without any DM and it worked fine.

SDDM itself running under X, here is a PR for supporting Wayland natively: https://github.com/sddm/sddm/issues/440

> LightDM doesn't work with any Wayland session: https://bugzilla.opensuse.org/show_bug.cgi?id=1156232
> 
> I have some fixes with the waybar and overall sway colors, maybe I will open PR.

Cool :) go ahead.

**Comment by itaranto** [comment]
> I was surprised about it, you just need to install it correctly :)
> I was able to install only minimal gdm dependencies with some tweaks. I need to recall what, but it is possible to avoid patterns-gnome-*

Ok, so it seems I need to tinker with the packages a little bit more.

> SDDM itself running under X, here is a PR for supporting Wayland natively: sddm/sddm#440

Good to know, I think most people will need X for compatibility anyway.
I always thought that the compositor is the one that implements Wayland, in this case, Sway.
So, you are saying, in the case of using GDM, both GDM and Sway are Wayland compositors?

**Comment by jubalh** [comment]
Pattern landed in [Factory](https://build.opensuse.org/package/show/openSUSE:Factory/patterns-sway)

**Comment by denisok** [comment]
@jubalh , I tested pattern.
I selected it during installation. What I have noticed - there is no Icon, when you are trying to select it during installation.

Then there are missing dependencies:
* Mesa
* alacritty

without Mesa I wasn't able to start sway.

**Comment by jubalh** [comment]
Thanks for testing!
Can you create SRs for the missing deps?

Right, I wanted to take care about the icon too. I didn't yet have time to dig up how it was done.
The icon isn't set in the pattern but in some other way and I'm not sure anymore how it works. Maybe it was in yast/installer directly.

**Comment by denisok** [comment]
yep, will do later.

I don't know how to set icon, but I will poke around.

**Comment by jubalh** [comment]
> I don't know how to set icon, but I will poke around.

No need, I found it :-)
Will update here once the requests are out.

**Comment by jubalh** [comment]
since https://github.com/denisok/openSUSEway/issues/2 tracks the theming/branding I'll rename this to pattern.

**Comment by jubalh** [comment]
Exactly :) I already started on it but didnt have enough time to finish it.

**Comment by jubalh** [comment]
> https://build.opensuse.org/request/show/811518

**Comment by denisok** [comment]
> I wouldn't use GDM since it pulls the ENTIRE GNOME DESKTOP when installing, even with --no-recommends.

--no-recommends gives me 137 packages on TW, without ~40.
137 doesn't look like entire gnome, it looks ok.

**Comment by jubalh** [comment]
https://github.com/jubalh/yast-theme/commit/fe70898fe10754384c36af45697ffb26fa849254 was merged two weeks ago.
But there seems an issue so they didn't update the factory package yet.

See discussion in https://github.com/yast/yast-theme/pull/128

**Comment by jubalh** [comment]
yast2-theme update on its way to Factory now: https://build.opensuse.org/request/show/816617

**Comment by jubalh** [comment]
![show-opensuseway-pattern](https://user-images.githubusercontent.com/1658215/86008723-764e1980-ba19-11ea-9792-98b819551fcf.png)

**Comment by denisok** [comment]
congrats! I also captured that couple of minutes ago :)

**Comment by lkocman** [comment]
Guys you've missed Leap completely. Let me add it as part of this one https://code.opensuse.org/leap/features/issue/68

**Comment by denisok** [comment]
@lkocman #7
