### ISSUE TITLE
reinstalling sway leaves config behind

### ISSUE THREAD

**Issue by denisok** [openSUSE/openSUSEway#10]
We have 50-openSUSE config file in config.d dir.

If someones uninstalls and installs new one, there would be `50-openSUSE.rpmsave` file left behind which is actually still valid for sway and it picks up both.

**Comment by m-rey** [comment]
How about renaming the `50-openSUSE` config to `50-openSUSE.conf` and only including `.conf` files in the sway config?
You'd have to also change the include in the sway config to `include /etc/sway/config.d/*.conf`

**Comment by denisok** [comment]
@m-rey good idea, would do that later, or you could branch package and do it )

**Comment by denisok** [comment]
and PR for this repo is required, to change that.

**Comment by denisok** [comment]
https://github.com/openSUSE/openSUSEway/releases/tag/0.4 @m-rey you can use that for package.

**Comment by denisok** [comment]
would be released here:
https://build.opensuse.org/request/show/820898
