### ISSUE TITLE
Remove mako dependency from patterns-sway

### ISSUE THREAD

**Issue by FilippoBonazziSUSE** [openSUSE/openSUSEway#103]
Also I found that `mako` is a strict dependency of the `patterns-sway` package, together with a few others. I was thinking we could remove that dependency, and possibly add `SwayNotificationCenter` as a Recommend rather than a strict dep... opinions?

_Originally posted by @FilippoBonazziSUSE in https://github.com/openSUSE/openSUSEway/discussions/81#discussioncomment-4839628_

**Comment by FilippoBonazziSUSE** [comment]
I'm not sure how to achieve this nicely - if there are any volunteers, please feel free to take this.

**Comment by jubalh** [comment]
Didn't follow the discussion closely.

But AFAIK sway per se doesn't require mako. So it would just be to remove `Requires: mako` in `X11:Wayland/patterns-sway`. Should I do that?
I would suggest to leave the notification out completely of the sway pattern and just pull in SwayNotificationthingy in the openSUSEway pattern.

**Comment by jubalh** [comment]
https://build.opensuse.org/request/show/1090297

**Comment by FilippoBonazziSUSE** [comment]
Nice. There are quite a few dependencies in the sway pattern which are arguable, to say the least. For almost each utility you could pick another equivalent one. We may want to do a wider cleanup of that pattern, and move our dependencies into the openSUSEway pattern.

**Comment by jubalh** [comment]
> There are quite a few dependencies in the sway pattern which are arguable, to say the least

Those were the only ones available at the beginning. First generation of those sway ecosystem tools :)

>  For almost each utility you could pick another equivalent one

This will always be the case. Quite often people who use a window manager will pick and select their favourite tools themselves. The sway pattern was created as a help to new users or users who wanted the (then) default tools installed in one go. We can't cover all the variantions, so people who like different tools probably will just start by manually installing them.

The big difference between the pattern and openSUSE way (created later) was that the latter provides everything nicely integrated with config files etc.

**Comment by jubalh** [comment]
Will close since SR got accepted to Factory.
