### ISSUE TITLE
alracritty config is not applied

### ISSUE THREAD

**Issue by denisok** [openSUSE/openSUSEway#11]
sway branding package is incorrect for alacritty, it seds incorrect file, it should modify base sway config.
I tried to `set $term` from config.d config file, but it didn't work.
Need more investigation:
* if there is posibility to reset $term under config.d
* maybe modify base sway config in %post

**Comment by m-rey** [comment]
Is this an alacritty specific issue that wouldn't happen with other terminals, like [kitty](https://github.com/kovidgoyal/kitty/)?

**Comment by denisok** [comment]
it is specific to openSUSE-branding packages for sway. If you use your custom sway configs, it shouldn't matter.
