### ISSUE TITLE
Greetd `style.css` file not packaged

### ISSUE THREAD

**Issue by FilippoBonazziSUSE** [openSUSE/openSUSEway#111]
I just noticed that the greetd `style.css` file, which is tracked in this repo, is not packaged in the spec file. greetd on a fresh openSUSEway install shows up bare (white/blue).

I think this might even be a regression, because I have the file under `/etc/greetd/style.css` on my system and I don't remember installing it manually. The file is not owned by any package right now, but it might be a leftover.

**Comment by denisok** [comment]
yeah, noticed that as well after the fresh install :) going to fix it
