### ISSUE TITLE
openSUSEway desktop

### ISSUE THREAD

**Issue by denisok** [openSUSE/openSUSEway#12]
is Tumbleweed based Desktop environment.
It is based on Wayland and sway.

**Comment by denisok** [comment]
new system role?
https://github.com/yast/skelcd-control-openSUSE/blob/master/control/control.openSUSE.xml#L336

**Comment by denisok** [comment]
@jubalh what do you think we should include in the desktop env?
browser
sudo,git, jq tools?

**Comment by denisok** [comment]
Something bare minimum that I would require to start: firefox, sudo, git, jq, wget, curl, vim (or whatever basic editor), tar, gzip, bzip2, less, grep, network manager.

**Comment by jubalh** [comment]
good question :)

What about pavucontrol/pulseaudio?
Depending on how DE like you want to have if vifm (file manager), alpine/mutt for mail, imv image viewer.

**Comment by jubalh** [comment]
I use mpv for videos.

**Comment by denisok** [comment]
> What about pavucontrol/pulseaudio?

that is already a dependency for waybar/pattern

**Comment by denisok** [comment]
GTK, QT themes?

(I leave it here as interesting example) https://github.com/kennylevinsen/dotfiles/blob/master/sway#L43

**Comment by m-rey** [comment]
I'd keep it fairly minimal, as many people like the simplicity and cleanliness of sway. https://github.com/openSUSE/openSUSEway/issues/12#issuecomment-651838166 covers the basics. Maybe add in `mpv` to the mix. I wouldn't choose a specific email client like alpine/mutt/neomutt/aerc, but just let the user decide.

**Comment by denisok** [comment]
maybe GTK and QT are out of scope, which means some default Adwaita or something. I don't care, but maybe there is some more fancy more basic theme that I am not aware of :)

e-mail client is hard, I think ppl that would use sway are knowledgeable enough to install what they need.

**Comment by jubalh** [comment]
I would definitely add mpv and imv.
What other use is it to create a "desktop" if you don't ship default applications?

Then people can just use the pattern or install by themselves.

**Comment by denisok** [comment]
OK first try here:
https://build.opensuse.org/request/show/820898

**Comment by denisok** [comment]
still I think we need to choose some GTK/QT themes, for example if I open pavucontrol it is all white by default, I would vote for the some dark theme.

**Comment by denisok** [comment]
some other packages we could add:
* command-not-found

**Comment by jubalh** [comment]
> still I think we need to choose some GTK/QT themes, for example if I open pavucontrol it is all white by default, I would vote for the some dark theme.

I agree. Not sure which is a nice and basic one though.

**Comment by denisok** [comment]
integrate wob from #17 to the pattern.

**Comment by denisok** [comment]
I think this is completed. openSUSEway pattern and desktop environment was added and is in Installation, where anyone could choose it from the start.
I am updating it to 0.8 and I think I close this one.

To get system role I have #19 .

@jubalh I suggest we remove openSUSE-branding from pattern-sway and add upstream-branding there instead.
So we would have clean, minimal sway upstream from your pattern and openSUSEway would have branding and all other packages.
What do you think?

**Comment by denisok** [comment]
update to 0.8:
https://build.opensuse.org/request/show/823705

that adds environments to get QT, GTK to support better Wayland.

That also adds wob for volume and brightness indicator.

**Comment by jubalh** [comment]
> @jubalh I suggest we remove openSUSE-branding from pattern-sway and add upstream-branding there instead.
So we would have clean, minimal sway upstream from your pattern and openSUSEway would have branding and all other packages.
What do you think?

Sure! Makes sense. In case I forget to do it feel free to send a SR.

**Comment by denisok** [comment]
@jubalh alright:
https://build.opensuse.org/request/show/823980

And latest desktop version also landed to Factory. closing this ticket!

**Comment by jubalh** [comment]
SR#823980 accepted, thanks!
