### ISSUE TITLE
patterns-openSUSEway missing fonts?

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSEway#125]
I started off with a plain MicroOS and installed patterns-openSUSEway. Starting sway works but no fonts are installed. I guess the pattern needs to either require the right ones or pull another pattern for that?

Note recommends are off on MicroOS so has to be a requirement

**Comment by jubalh** [comment]
Comparing with the [LXQt pattern](https://build.opensuse.org/package/view_file/X11:LXQt/patterns-lxqt/patterns-lxqt.spec?expand=1) I see it `Requires:       pattern() = x11`.
And [that one](https://build.opensuse.org/package/view_file/openSUSE:Factory/patterns-base/patterns-base.spec?expand=1) seems to `Requires:       xorg-x11-fonts-core`.
So I assume that's how they get the fonts that are shipped with X11.

Probably we need something similar for us on Wayland. Choosing some font?

**Comment by denisok** [comment]
You are right, we should do that.

So far we explicitly specify fonts in: 
  - waybar config: `font-family:   "Source Sans Pro", "FontAwesome 6 Free";`
  - swaync: ` font-family: "Source Sans Pro";`


Right now we have this requirement:
```
Requires:       fontawesome-fonts
```

Actually is doesn't work for me too, system just pick some font, but what we need is `adobe-sourcesanspro-fonts`. I will create a patch.

**Comment by lnussel** [comment]
There's a fonts pattern too. I've filed https://build.opensuse.org/request/show/1119623

**Comment by denisok** [comment]
> Comparing with the [LXQt pattern](https://build.opensuse.org/package/view_file/X11:LXQt/patterns-lxqt/patterns-lxqt.spec?expand=1) I see it `Requires: pattern() = x11`. And [that one](https://build.opensuse.org/package/view_file/openSUSE:Factory/patterns-base/patterns-base.spec?expand=1) seems to `Requires: xorg-x11-fonts-core`. So I assume that's how they get the fonts that are shipped with X11.
> 
> Probably we need something similar for us on Wayland. Choosing some font?

yeah, in Wayland we probably don't want to require x11. Installing any font will get xorg-x11-fonts-core as a dependency.

I would just get the basic ones that we explicitly require in configs, and let the user choose and configure any other ones. I personally have `jetbrains-mono` for my terminal.

**Comment by FilippoBonazziSUSE** [comment]
Yes, I would be against adding additional `Requires` other than the two we use in the default config (Fontawesome and Source Sans Pro). It would just result in unremoveable dependencies for users who choose to use other fonts - a problem we already have for some packages in this pattern (`mako` comes to mind).
We intentionally list useful or suggested packages as `Recommends` to avoid exactly this.

I see why not installing `Recommends` is the default on MicroOS. However it breaks on such cases where flexibility is desired. And moving `Recommends` to `Requires` as a consequence would be counterproductive.

**Comment by lnussel** [comment]
Recommends are broken for OS components really. Imagine /usr was an image as in other modern OSes. No recommends there. Either components are part of the OS or they aren't.

**Comment by denisok** [comment]
added fonts as part of: https://github.com/openSUSE/openSUSEway/pull/133
