### ISSUE TITLE
Screen sharing

### ISSUE THREAD

**Issue by denisok** [openSUSE/openSUSEway#13]
https://wiki.archlinux.org/index.php/PipeWire#WebRTC_screen_sharing

https://github.com/emersion/xdg-desktop-portal-wlr
https://github.com/flatpak/xdg-desktop-portal

https://github.com/swaywm/sway/issues/4358

https://pipewire.org/

**Comment by denisok** [comment]
> I'm trying to get screen sharing working with xdg-desktop-portal-wlr and chromium. Chromium has the enable-webrtc-pipewire-capturer flag enabled. I installed pipewire (distro package) and compiled xdg-desktop-portal-wlr myself. When I go to the mozilla getUserMedia test page and click the Screen Capture button, chromium prompts me to choose what I want to share, but I see no screens or windows that I could share
> 03:56 <Arnavion> When I click that button I do see pipewire, xdg-desktop-portal and xdg-desktop-portal-wlr start up, and they stay running successfully
> 03:56 <Arnavion> There is no output from chromium that would indicate something is wrong. How can I debug this?
> 04:11 <Arnavion> Actually, it looks exactly like   https://bugs.chromium.org/p/chromium/issues/detail?id=1067113   The invisible window mentioned in step 7 is indeed there. And indeed I now see the wiki note says that Arch's Chromium needs libpipewire02, so it must be the same problem with my distro's package
> 05:53 <Arnavion> Actually actually, my distro specifically patches chromium to compile with pipewire 0.3 instead of 0.2 using a patch that fedora also carries, and apparently screensharing is supposed to work with that patch. But that patch was broken until a few hours ago, heh
> 05:53 <Arnavion> That was one heck of a merry-go-round

**Comment by agraul** [comment]
I think this is also related: https://www.reddit.com/r/swaywm/comments/hlwalf/question_why_was_rdp_removed_from_sway/ (https://github.com/swaywm/wlroots/pull/1988)

Another piece of resource I found: https://soyuka.me/make-screen-sharing-wayland-sway-work/

**Comment by agraul** [comment]
I just saw that `xdg-desktop-portal-wlr` is on its way to Tumbleweed https://build.opensuse.org/request/show/820843

**Comment by denisok** [comment]
so I installed `xdg-desktop-portal-wlr` and it works. At least I can share current screen. If there are more screens, there is no choice to make.

**Comment by denisok** [comment]
https://github.com/swaywm/sway/pull/5607
for systemd, and I would update profile.d to set it there as well.

**Comment by denisok** [comment]
https://github.com/emersion/xdg-desktop-portal-wlr/issues/12

**Comment by denisok** [comment]
So actually only thing that is need to be setup correctly is the `XDG_SESSION_TYPE` if sway starts from tty.
Graphical login managers, like GDM do set it correctly.

For tty this needs to be landed:
https://github.com/swaywm/wlroots/pull/2304

**Comment by denisok** [comment]
https://build.opensuse.org/request/show/824519
submitted dependencies to the OBS.
`XDG_SESSION_TYPE` for the tty would be fixed upstream.
