### ISSUE TITLE
Consider shipping /usr/etc/xdg-desktop-portals/sway-portals.conf

### ISSUE THREAD

**Issue by Arnavion** [openSUSE/openSUSEway#134]
This is xdp's new preferred way to handle portals that have partial implementations, like xdpw is, and delegate unsupported features to other portals.

Ref:

- [xdp documentation](https://github.com/flatpak/xdg-desktop-portal/blob/1.18.2/doc/portals.conf.rst.in)

- [Suggested example in xdpw repo](https://github.com/emersion/xdg-desktop-portal-wlr/blob/v0.7.1/contrib/wlroots-portals.conf)

- [xdpw discussion and link to xdp PR](https://github.com/emersion/xdg-desktop-portal-wlr/pull/269)

- [GNOME desktop's file](https://gitlab.gnome.org/GNOME/gnome-session/-/blob/9aee6320d6e0002cf2f097ca0393af9aa6cb1757/data/gnome-portals.conf)

For openSUSEway's case, I believe the xdpw example would be correct, ie use xdpw for screenshot and screencast but delegate everything else to xdp-gtk.

**Comment by Arnavion** [comment]
Oh, I did not check in sway package itself or in `/usr/share/`. Sorry for noise.

**Comment by denisok** [comment]
no problem! Thanks for caring! :)

**Comment by denisok** [comment]
btw - I see new "portals" dir - maybe that should be fixed and sway and wlr files should be moved?

**Comment by Arnavion** [comment]
The `/usr/share/xdg-desktop-portal/sway-portals.conf` path is correct. It is what the xdp doc says and also what [the code looks for.](https://github.com/flatpak/xdg-desktop-portal/blob/1.18.2/src/portal-impl.c)

The `portals` subdirectory is where portals themselves, like xdpw, drop their `UseIn=` files.
