### ISSUE TITLE
Replace chameleon logo with numbers in waybar 

### ISSUE THREAD

**Issue by antisocrates** [openSUSE/openSUSEway#141]
The waybar workspaces without numbers indicating the workspace is very confusing.

For example, if you open a terminal, in workspace 1, 2, 3 you can see at a glance which one is open. Mod+1 for 1st, mod+2 for 2nd etc.

Now if you close the terminal in workspace 2. It's not so apparent unless you remember which workspace is which. Mod+1 takes you to the 1st, Mod+2 opens a new workspace. Which number is the other open workspace?
Will have to try 3 to 9 to check.

This is counterproductive and makes no sense, please revert to something like the default waybar for workspaces.

P. S. : It can be changed by the user, but it  adds an extra burden for new installs, as it's unusable out of the box, and not user friendly as the project aims to be.

Bonus: smart_gaps on, should be the default for single windows to maximize screen estate usage.

**Comment by FilippoBonazziSUSE** [comment]
If you want to open a PR with these changes, feel free to. Otherwise I can get to it sometime this week hopefully.

**Comment by denisok** [comment]
they are cute though )))) I don't mind the change. Maybe leave one icon on the left as a icon, either that just does nothing or maybe assign `wofi` to it

**Comment by FilippoBonazziSUSE** [comment]
I'm planning to submit a change like I have in my configuration, with the active workspace having the geeko and number, and the inactive ones having just the number:
![20240226_10h05m22s_grim](https://github.com/openSUSE/openSUSEway/assets/101266837/be3728ca-454a-4b4f-bc3b-5f7c74c254da)

Opinions welcome about `smart_gaps` as I don't use gaps at all so I don't know

**Comment by FilippoBonazziSUSE** [comment]
Yes. It's because 3 is the active workspace and has the geeko. This is how it's done in my config:
```json
    "sway/workspaces": {
        "format": "{index} {icon}",
        "format-icons": {
            "urgent": "",
            "focused": "",
            "default": ""
        }
    }
```

The geeko icon does not show here but it's this one: https://fontawesome.com/icons/opensuse?f=brands&s=solid

**Comment by jubalh** [comment]
> with the active workspace having the geeko and number
That's cool!
I am personally against removing the geeko altogether, it's nice!

**Comment by denisok** [comment]
> Yes. It's because 3 is the active workspace and has the geeko.

where is 4 ? :)

**Comment by FilippoBonazziSUSE** [comment]
Ah, it's just not there. I didn't create it, that's just my workflow. Sorry I see how that could be confusing. The screenshot only contains workspaces 1, 3, 5 and 6.

**Comment by FilippoBonazziSUSE** [comment]
I've transfered your `smart_gaps` suggestion to a [poll](https://github.com/openSUSE/openSUSEway/discussions/144).

Please try to keep issues limited to a single topic.
