### ISSUE TITLE
Default `.bashrc`  is too barebones

### ISSUE THREAD

**Issue by markosx32** [openSUSE/openSUSEway#145]
Currently .bashrc is way too barebones, as it doesn't have any coloring. 
I suggest adding a minimal PS1 and ls=ls --color=auto by default:

.alias:
`alias ls='ls --color=auto'`

.bashrc
`export PS1="\[\e[38;5;34m\]\u\[\e[38;5;40m\]@\[\e[38;5;46m\]\h:\[\e[38;5;154m\]\w $\[\033[0m\] "`

**Comment by FilippoBonazziSUSE** [comment]
Hi, we are not shipping a `.bashrc` or any other shell-related customization. I believe that shell configuration is very individual, and is best left up to the user.

For example I use ZSH (like probably a sizable part of our users do), so having a default Bash configuration would be useless for me. I am leaving this open to collect opinions from others.

**Comment by jubalh** [comment]
@markosx32 if you want a preconfigured shell config with some nice features I suggest you try `grml-zsh-config` (available in default repos).
