### ISSUE TITLE
Waybar modul "custom/zypper" dont work (solution in this issue)

### ISSUE THREAD

**Issue by 42web-ch** [openSUSE/openSUSEway#169]
Hi, i found a typo:

In the waybar config:

` "custom/zypper": {
        "format": "{} ",
        "interval": 3600,
        "exec": "zypper lu | grep 'v |' | wc -l; echo 'packages to update'",
        "exec-if": "exit 0",
        "on-click": "exec alacritty -e sudo sh -c 'zypper ref; zypper dup; pkill -SIGRTMIN+8 waybar'",
        "signal": 8
    },`

Here at the grep:
exec": "zypper lu | grep **'v |'** | wc -l; echo 'packages to update'

Its need one space more between `v |` 

My OS: OS: openSUSE Tumbleweed 20240829 x86_64

**Comment by FilippoBonazziSUSE** [comment]
I'm sorry, I don't understand your report. This is the openSUSEway waybar config:
```json
    "custom/zypper": {
        "format": "{} ",
        "interval": 3600,
        "exec": "zypper lu | grep 'v |' | wc -l; echo 'packages to update'",
        "exec-if": "exit 0",
        "on-click": "exec alacritty -e sudo sh -c 'zypper ref; zypper dup; pkill -SIGRTMIN+8 waybar'",
        "signal": 8
    },
```

The command `zypper lu | grep 'v |' | wc -l` works and returns the expected value.

Where is the typo?

**Comment by FilippoBonazziSUSE** [comment]
Looks like something changed in the zypper output format. Thanks for the report
