### ISSUE TITLE
Try and add wob package

### ISSUE THREAD

**Issue by denisok** [openSUSE/openSUSEway#17]
https://github.com/francma/wob

**Comment by m-rey** [comment]
https://build.opensuse.org/package/show/home:mrey/wob

Feedback, improvements, comments and obs requests are very welcome.

**Comment by jubalh** [comment]
Looking good! You can push it to a devel

**Comment by jubalh** [comment]
https://build.opensuse.org/request/show/823286 accepted to X11:Wayland

**Comment by m-rey** [comment]
Now also available in Factory! https://build.opensuse.org/package/show/openSUSE:Factory/wob

**Comment by denisok** [comment]
@m-rey thanks! will try it and probably integrate in openSUSEway pattern.
