### ISSUE TITLE
Tumbleweed moved to new background

### ISSUE THREAD

**Issue by FilippoBonazziSUSE** [openSUSE/openSUSEway#175]
> denisok:
> yaks, duped today, and scheme doesn't work. Looks like background images are reset. will fix later
> yeah, path changed /usr/share/wallpapers/default-1920x1080.png now :
> ```
> stdden@stdlen:~> ls -la /usr/share/wallpapers/
> total 20
> drwxr-xr-x 1 root root  214 Oct 27 09:06 .
> dr-xr-xr-x 1 root root 2574 Oct 14 09:02 ..
> lrwxrwxrwx 1 root root   22 Oct  3 11:42 default.png -> openSUSEtumbleweed.png
> -rw-r--r-- 1 root root   25 Oct  3 11:42 default.png.desktop
> drwxr-xr-x 1 root root   70 Oct 27 09:06 openSUSEdefault
> lrwxrwxrwx 1 root root   43 Oct  3 11:42 openSUSEtumbleweed.png -> openSUSEdefault/contents/images/default.png
> -rw-r--r-- 1 root root  110 Oct  3 11:42 openSUSEtumbleweed.png.desktop
> lrwxrwxrwx 1 root root   15 Oct  3 11:42 SLEdefault -> openSUSEdefault
> stdden@stdlen:~> ls -la /usr/share/wallpapers/openSUSEdefault/
> total 124
> drwxr-xr-x 1 root root     70 Oct 27 09:06 .
> drwxr-xr-x 1 root root    214 Oct 27 09:06 ..
> drwxr-xr-x 1 root root     12 Oct  3 11:42 contents
> -rw-r--r-- 1 root root    287 Oct  3 11:42 metadata.json
> -rw-r--r-- 1 root root 118817 Oct  3 11:42 screenshot.png
> stdden@stdlen:~> ls -la /usr/share/wallpapers/openSUSEdefault/contents/images/
> total 612
> drwxr-xr-x 1 root root     80 Oct 27 09:06 .
> drwxr-xr-x 1 root root     12 Oct  3 11:42 ..
> lrwxrwxrwx 1 root root     11 Oct  3 11:42 1920x1200.png -> default.png
> -rw-r--r-- 1 root root 431187 Oct  3 11:42 default-dark.png
> -rw-r--r-- 1 root root 188014 Oct  3 11:42 default.png
> ```

**Comment by FilippoBonazziSUSE** [comment]
`alacritty.toml`:
```toml
[window]
opacity = 0.8
```

![image](https://github.com/user-attachments/assets/a34b6ee1-25fe-49a8-b31a-525997923b8a)

**Comment by FilippoBonazziSUSE** [comment]
`alacritty.toml`
```toml
[window]
opacity = 0.6
```

Maybe still a bit too light

![image](https://github.com/user-attachments/assets/7a433f88-64c7-4def-8d88-6bfabe2b71c4)

**Comment by FilippoBonazziSUSE** [comment]
`alacritty.toml`
```toml
[window]
opacity = 0.7
```
Looks fine to me.

![image](https://github.com/user-attachments/assets/ca5e1af0-d1ee-4815-81c1-cf2a8f960cbd)

**Comment by FilippoBonazziSUSE** [comment]
The theme colours still look fine to me, I don't think we need to change anything in that regard.

**Comment by FilippoBonazziSUSE** [comment]
Question: do we want to adjust the background colour / opacity of waybar as well?

I would propose changing the waybar bagrkound colour to the main background colour (dark green rgb(12,42,39)), so that the bar looks transparent without colour change

**Comment by FilippoBonazziSUSE** [comment]
After some more experiments, I think `0.75` alacritty opacity looks better. I will create a PR with that

**Comment by FilippoBonazziSUSE** [comment]
`greetd` does not look good at all with the new background, especially the clock:
![image](https://github.com/user-attachments/assets/fbf08c7f-7d5f-4f9f-b0f6-9f0868e2d56e)

**Comment by denisok** [comment]
you can play with font and size in css, or make it pitch black for example, or you can take any color from the official pallet for the backgound. It doesn't matter that much for the login, ppl don't see it that often.

**Comment by FilippoBonazziSUSE** [comment]
Added a dark shadow on top, now looks like this:
```css
window {
	background-image: url("file:///usr/share/wallpapers/openSUSEdefault/contents/images/default-dark.png");
	background-size: cover;
	background-position: center;
	color: rgba(53, 185, 171, 1);
	box-shadow: inset 0 0 0 8000px rgba(1, 1, 1, 0.4);
}
```
![image](https://github.com/user-attachments/assets/52e86a25-6000-44dc-97a4-011d985f1aeb)

**Comment by FilippoBonazziSUSE** [comment]
Note for future tinkering: run GTK apps in debug mode with the GTK inspector:
```shell
GTK_DEBUG=interactive gtkgreet
```
I didn't know this and it's really cool
