### ISSUE TITLE
Update wayvnc to 0.2.0 and its dependencies

### ISSUE THREAD

**Issue by agraul** [openSUSE/openSUSEway#18]
- wayvnc: https://github.com/any1/wayvnc/releases/tag/v0.2.0
- neatvnc: https://github.com/any1/neatvnc/releases/tag/v0.2.0
- aml (required by neatvnc 0.2.0): https://github.com/any1/aml/releases/tag/v0.1.0

**Comment by agraul** [comment]
Requests to X11:Wayland: 824743, 824744, 824745

**Comment by jubalh** [comment]
Thanks! All accepted and forwarded to Factory.
