### ISSUE TITLE
Create openSUSE brand packages

### ISSUE THREAD

**Issue by denisok** [openSUSE/openSUSEway#2]
- [x] swaywm
- [x] strip user specific settings from waybar conf in this repo
- [x] waybar
- [x] alacritty
- [x] wofi

https://opensuse.github.io/branding-guidelines/

**Comment by denisok** [comment]
here is a first try for Sway:

https://build.opensuse.org/package/show/home:dkondratenko/sway-branding-openSUSE
https://build.opensuse.org/package/show/home:dkondratenko:branches:X11:Wayland/sway

I haven't tested it yet. And I am adding dependencies that I have in config (like term and app launcher).

Also I need to check if we need branding at all, or it could be just theme, if all modifications in `sway/config.d` are working.

**Comment by denisok** [comment]
openSUSEway brandings: https://build.opensuse.org/request/show/811874
waybar with upstream branding: https://build.opensuse.org/request/show/811850
sway with upstream branding: https://build.opensuse.org/request/show/811849

**Comment by denisok** [comment]
@jubalh check it out :)

I am a little bit confused so far how we would build dependency tree.
On what would depend on what.

**Comment by denisok** [comment]
@jubalh : https://build.opensuse.org/request/show/816069 branding as recommends to the pattern.

**Comment by jubalh** [comment]
@denisok accepted :)

**Comment by denisok** [comment]
Thanks!

Now lets see what Factory would say.

https://build.opensuse.org/request/show/816082

**Comment by denisok** [comment]
@jubalh I need changes to the X11:Wayland Project config, so build could resolve correct branding:
```
Prefer: sway-branding-upstream
Prefer: waybar-branding-upstream

# try to prevent cycles
Prefer: -sway-brandingopenSUSE
Prefer: -waybar-branding-openSUSE
```

**Comment by jubalh** [comment]
@jengelh ^

**Comment by denisok** [comment]
hm, something changed and now fixed.. not sure what

**Comment by denisok** [comment]
![20200630_09h57m15s_grim](https://user-images.githubusercontent.com/1289121/86099755-32f6b800-bab8-11ea-9754-1ba035621b5c.png)

**Comment by denisok** [comment]
brandig has landed, there are few bugs, but they are tracked separately.
