### ISSUE TITLE
Icon for openSUSEway

### ISSUE THREAD

**Issue by denisok** [openSUSE/openSUSEway#20]
Right now openSUSEway pattern points to the same icon as pattern-sway.

It might be confusing, so I suggest we customize that icon with some openSUSe mascot, or have some new icon.

@jubalh @m-rey @agraf if you have any ideas or know ppl with design skills - bring it on :)

**Comment by agraul** [comment]
@hellcp do you have time and are looking to pick something else up? Now that you are on the board you *must* have a lot of free time ;P

**Comment by hellcp** [comment]
I'm surprised I wasn't pinged earlier ;)

**Comment by hellcp** [comment]
Let's start with something simple, pattern icon that fits the rest of the icons:
https://gist.github.com/hellcp/2b8e424fd27f9fe2088cd68f9f71797f

Now from this we can go two ways, subicon with geeko button like pattern-$desktop-$type icons in yast-theme (https://github.com/yast/yast-theme/blob/master/icons/hicolor/scalable/apps/pattern-kde-addon.svg), or openSUSE green instead of the green used here

**Comment by denisok** [comment]
I have no idea about design :))  but I like it.
Geeko button means geeko there ?

maybe you can take a look into the whole openSUSEway design and propose some better color schemes and etc..

**Comment by hellcp** [comment]
Buttons are those things we use for small size artwork to represent something openSUSE related https://github.com/openSUSE/artwork/blob/master/logos/buttons/button-colour.svg

**Comment by jubalh** [comment]
> maybe you can take a look into the whole openSUSEway design and propose some better color schemes and etc..

@hellcp here would be a screenshot of that: https://en.opensuse.org/File:Sway_openSUSE_15.2.png

**Comment by hellcp** [comment]
Well, the fact that Leap 15.2 version is using TW wallpaper, it's a touch troubling, I don't have much more feedback

**Comment by denisok** [comment]
openSUSEway supports only TW, that just weird name )

**Comment by denisok** [comment]
@hellcp Thanks for doing it, I installed recently on VM new system and it looks cool!

https://github.com/yast/yast-theme/blob/master/icons/hicolor/scalable/apps/pattern-sway.svg
https://github.com/yast/yast-theme/blob/master/icons/hicolor/scalable/apps/pattern-sway-openSUSE.svg
