### ISSUE TITLE
Allow root app to run on the user session

### ISSUE THREAD

**Issue by denisok** [openSUSE/openSUSEway#21]
Gnome and KDE on Wayland allow to run some app that need root permission under the same session. How they do it?

Is that some Polkit feature?

**Comment by agraul** [comment]
I think GNOME uses `libgnomesu` for that, but I don't know how it works.

**Comment by denisok** [comment]
need to add `polkit-gnome` package and this to conf:
`exec /usr/libexec/polkit-gnome-authentication-agent-1`

**Comment by denisok** [comment]
added to spec here:
https://build.opensuse.org/request/show/864374
