### ISSUE TITLE
Do not force Qt Theme

### ISSUE THREAD

**Issue by itaranto** [openSUSE/openSUSEway#24]
Do not force Qt Theme in /etc/sway/env or /usr/lib/environment.d/50-openSUSE.conf.
Thanks.

**Comment by denisok** [comment]
I have forced it just to get understanding about what Sway openSUSE distro is about ?
Just Sway without any tuning is a different thing, usually theming is there to kind get all together.

Maybe something like "prefer" some dark theme in QT is more appropriate, if there is such thing.

What do you think?

**Comment by itaranto** [comment]
It makes sense to have good defaults, but they should be "overridable".

Anyway I'm sad to admit I'm using Arch Linux in my main machine right now LOL.

So, I don't think I will be of much help here. Good Luck!

**Comment by m-rey** [comment]
I was using sway already before installing openSUSEway. After the installation, suddenly everything was in dark theme. This was unexpected for me. I'd recommend to at least allow to choose between light and dark variants of the sway openSUSE distro.

Documenting what the openSUSEway package does and how certain things can be changed (eg the theme) would be very helpful.

**Comment by jubalh** [comment]
> I was using sway already before installing openSUSEway. After the installation, suddenly everything was in dark theme. This was unexpected for me.

This happens with all other DEs too. If you choose to install a variant with special configs this is what will happen..

**Comment by m-rey** [comment]
> This happens with all other DEs too.

Indeed, I completely agree.

Just wanted to mention why I would like openSUSEway to have more documentation. It's okay that some defaults are set, but it would be nice to document how the default config can be changed as a short FAQ or something like that.

**Comment by denisok** [comment]
@m-rey :
https://en.opensuse.org/Portal:OpenSUSEway
https://en.opensuse.org/Portal:OpenSUSEway/Configuration

it is documented a little bit. I could add more, what do you think is missed?

As for QT scheme, I think there is a way to configure it through the ini config file. I forced it with env var just for simplicity :) I would check if I can customize correctly with configs.

**Comment by denisok** [comment]
alright, solution for this is to use `qt5ct` config file, setting it on system level at `/etc/xdg/qt5ct/qt5ct.conf`:
```
[Appearance]
color_scheme_path=/usr/share/qt5ct/colors/darker.conf
custom_palette=true
standard_dialogs=gtk2
style=Adwaita-Dark

```
We already have `QT_QPA_PLATFORMTHEME=qt5ct` so it would set correct theme.

I will submit patch.

**Comment by denisok** [comment]
packages on their way (sway-branding-openSUSE to change env and openSUSEway with `qt5ct.conf`):
https://build.opensuse.org/request/show/830582
