### ISSUE TITLE
The openSUSEWay package does not play good with X Sessions

### ISSUE THREAD

**Issue by itaranto** [openSUSE/openSUSEway#25]
I see there are two places in which some Wayland-specific environment variables are set: /etc/sway/env and /usr/lib/environment.d/50-openSUSE.conf.

This breaks some applications if you are using an X-based desktop/WM, in my case I use i3 aside from Sway.

This configuration should be Sway-only, it should not pollute the env vars for every other session.

**Comment by denisok** [comment]
I would like, but what is the way 

 I would say maybe openSUSEway is more for the newcomers that just install it from scratch as a first step into the tiling wm.
patterns-sway-sway doesn't do this crazy tunes.

**Comment by itaranto** [comment]
I get your point. I appreciate your effort to make it easier to run Sway on openSUSE.

Feel free to close this if you want.

**Comment by denisok** [comment]
I think the better way is maybe running DE in container, when it doesn't affect any other DEs in the system. So far I have updated the doc: https://en.opensuse.org/Portal:OpenSUSEway to define incompatibility with other DEs.

If ppl want just to try Sway better way is just https://en.opensuse.org/Sway .

**Comment by denisok** [comment]
fixed by #29
