### ISSUE TITLE
Cannot copy and paste from/to chromium browser

### ISSUE THREAD

**Issue by jm2dev** [openSUSE/openSUSEway#26]
I find impossible to copy/paste anything in chromium browser. It works fine (CTRL+C, CTRL+V, selection and mouse middle button).

I installed swaywm as instructed per the README file, on a vanilla opensuse tumbleweed system.

**Comment by jubalh** [comment]
I have the same problem on Firefox under GNOME Wayland.
AFAIK it's a common problem that sometimes happens under Wayland but I'm not sure about the details.

**Comment by jm2dev** [comment]
Thanks for your response.
It probably works for me because of the environment variables defined in the env file, and I wonder if another one is required for chromium to work. So far I haven't found a satisfactory solution, other than open a plain text file in chromium to paste content from, which isn't ideal.

**Comment by denisok** [comment]
hm, I don't use Chromium, but could reproduce. I could copy-paste inside chromium, and actually from chromium to some apps, for example Telegram, Visual Studio Code.

I see with `xeyes` that Chromium is running in X mode, Code as well, but Telegram is not....

**Comment by denisok** [comment]
BTW I tried Chrome and it works fine, so looks like Chromium misses some components.

https://bugs.chromium.org/p/chromium/issues/detail?id=986835

**Comment by denisok** [comment]
looks like Chromium is built with wayland support.

But who knows what bug is it:
https://bugs.chromium.org/p/chromium/issues/list?q=clipboard%20wayland

**Comment by denisok** [comment]
@jm2dev I would close this if you don't mind, that is bug for upstream (Chromium). Feel free to reopen,
