### ISSUE TITLE
default login manager for openSUSEway

### ISSUE THREAD

**Issue by denisok** [openSUSE/openSUSEway#27]
I have an idea of lightweight and basic login manager that will work better with sway.

I think greetd with gtkgreet could become such:
https://build.opensuse.org/request/show/833018
https://build.opensuse.org/request/show/833019

That could also avoid setting env inside profile or environment and set it from the greeter instead.

**Comment by denisok** [comment]
@jubalh @agraul @m-rey what would you think about greetd as default login manager ? 

Adding `gfxboot` to openSUSEway pattern would make it complete DE experience from boot to login to sway :)

**Comment by denisok** [comment]
I use it locally now, and it works just fine, I replaced GDM with it, and I notice almost no difference, except that it is faster.

**Comment by jubalh** [comment]
Oh nice! I wasn't aware of those projects!
I'm all for it. Do you have any picture previews or video?

**Comment by m-rey** [comment]
Sounds like a good idea!

**Comment by denisok** [comment]
@jubalh will try it on VM and attach some :)

**Comment by denisok** [comment]
![20200910_10h28m31s_grim](https://user-images.githubusercontent.com/1289121/92701732-a175b300-f350-11ea-8303-68b902d67f18.png)

**Comment by denisok** [comment]
tui greet:
![20200910_11h33m46s_grim](https://user-images.githubusercontent.com/1289121/92712351-cae70c80-f359-11ea-97e2-3d2dc3011581.png)

**Comment by jubalh** [comment]
Cool! In the past I had an item on my todo list to write such an application myself. Now I can check that off ;D
