### ISSUE TITLE
Remove dmenu as dependency for patterns-sway-sway

### ISSUE THREAD

**Issue by itaranto** [openSUSE/openSUSEway#30]
**patterns-sway-sway** already contains wofi, which is an application launcher, so dmenu does not make much sense.

I didn't know were to post this, please let me know if [bugzilla](https://bugzilla.opensuse.org/enter_bug.cgi) is a better place for tracking this.

**Comment by denisok** [comment]
It is fine here. Will do next time I will be submitting something to OBS.

**Comment by jubalh** [comment]
https://build.opensuse.org/request/show/836046
