### ISSUE TITLE
Include pamixer in the pattern

### ISSUE THREAD

**Issue by dionisiovj** [openSUSE/openSUSEway#32]
The sway configuration (/etc/sway/config.d/50-openSUSE.conf) uses pamixer to control the volume, however it is not included in the pattern (running Tumbleweed).

After manually installing with zypper, everything works as expected

**Comment by jubalh** [comment]
How did you install openSUSEway?
https://build.opensuse.org/package/view_file/X11:Wayland/openSUSEway/openSUSEway.spec?expand=1 line 51 adds pamixer.

**Comment by dionisiovj** [comment]
Sorry, I confused `sway-branding-openSUSE` with `openSUSEway` (I installed the former). I am new to openSUSE so I don't know if you are also in charge of the patterns/branding/wiki but here are a couple suggestions in case any of them is possible:
- Move `pamixer` to `sway-branding-openSUSE`: The sway configuration file that uses `pamixer` is included in this package and other dependencies like `pavucontrol` and `brightnessctl` are required/specified  there too.
- Change the wiki (https://en.opensuse.org/Sway) to recommend installing `openSUSEway` instead of `sway-branding-openSUSE`.

**Comment by denisok** [comment]
Hi @dionisiovj,

nice catch. I would further separate conf file, so pamixer part of it would be installed only with openSUSEway, so it wouldn't be confusing for ppl that just want some visual "sway" branding only.

Thanks,
Denys

**Comment by denisok** [comment]
looked on specs and decided that right way to go is to add dependencies to spec as @dionisiovj suggested.
Here are missed dependencies (from conf file) added:
https://build.opensuse.org/request/show/864374

If there would be no objection or some review - I would land it tomorrow.

**Comment by jubalh** [comment]
Did you remove it (and the config) from sway-branding-openSUSE ?

**Comment by denisok** [comment]
I added missed packages to the sway-branding-openSUSE, it doesn't affect standard sway patterns.
That conf also installed only with sway-branding-openSUSE.

**Comment by jubalh** [comment]
What about:

> I would further separate conf file, so pamixer part would be installed only with openSUSEway, so it wouldn't be confusing for ppl that just want some visual "sway" branding only.

Sounded reasonable to me.

**Comment by denisok** [comment]
> Sounded reasonable to me.

I looked into it, and there is already brightness control and etc. So actually it customizes Sway in a good way.

openSUSEway is more about DE env, including browser and etc.

Removing wob, brightness, pamixer and other stuff leaves almost none branding Sway experience.

**Comment by denisok** [comment]
OK, it is is on its way to Factory: https://build.opensuse.org/request/show/864611
