### ISSUE TITLE
sway branding upgrade: java problems

### ISSUE THREAD

**Issue by bobblkabb** [openSUSE/openSUSEway#35]
Upgrading sway-branding-openSUSE from 0.12-2.1 to 0.13-1.1 messes java applications up. SAPGui for Java and Freeplane doesn't work properly anymore.
More info on my [bug report](https://bugzilla.opensuse.org/show_bug.cgi?id=1181545).

**Comment by denisok** [comment]
Thank for the report, I will take a look this weekend

**Comment by denisok** [comment]
answered in bug report, that maybe dues to env variables:
https://wiki.archlinux.org/index.php/Sway#Java_applications

depends on how you start sway.

**Comment by denisok** [comment]
fixed in https://bugzilla.opensuse.org/show_bug.cgi?id=1181545

environment is not set, it should be either set by sway-branding-openSUSE scripts or manually:
https://github.com/swaywm/sway/wiki/Systemd-integration
