### ISSUE TITLE
add some applications to default floating

### ISSUE THREAD

**Issue by mcepl** [openSUSE/openSUSEway#38]
Specifically, I suggest adding:
```
# Window settings
for_window [app_id="gnome-calculator"] floating enable
for_window [app_id="zenity"] floating enable
```
to ``/etc/sway/config.d/50-openSUSE.conf``, because these two applications (something more?) should be obviously floating by default.

**Comment by m-rey** [comment]
I have some custom floating rules in my dotfiles: https://github.com/m-rey/dotfiles/blob/master/dot_config/sway/config.d/window_rules

Maybe we could add some of them. Some useful ones are:
```
for_window [app_id="pavucontrol"] floating enable, sticky enable, resize set width 550 px height 600px, move position cursor, move down 330
for_window [app_id="nm-connection-editor$"] floating enable
for_window [title="^Open File$"] floating enable
for_window [app_id="firefox" title="Choose User Profile$"] floating enable
for_window [window_role="GtkFileChooserDialog"] resize set 800 600, move position center
for_window [window_role="pop-up"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_role="task_dialog"] floating enable
for_window [window_role="Preferences"] floating enable
for_window [window_type="dialog"] floating enable
for_window [window_type="menu"] floating enable
for_window [instance="update_installer"] floating enable

**Comment by denisok** [comment]
I think that is a good idea, if you could submit PR with it - will be cool. Something like `60-openSUSE-apps.conf` or something like that.

**Comment by m-rey** [comment]
good idea! I'll do that soonish. Feel free to suggest more entries!
For example something like:
```
for_window {
  [app_id="firefox" title="Firefox - Sharing Indicator"] floating enable
  [app_id="firefox" title="Picture-in-Picture"] floating enable, sticky enable
}
```

I'd like to figure out how to move the sharing indicator to the top part of the screen, instead of it being exactly in the center, before submitting a PR. Any suggestions?

**Comment by denisok** [comment]
I actually to lazy to use any of that :) I have nothing, so whatever you come with - I would use it :)

**Comment by denisok** [comment]
@krishjainx Sure, go ahead - please leave some general one's that have been installed with https://build.opensuse.org/package/view_file/X11:Wayland/openSUSEway/openSUSEway.spec?expand=1

**Comment by FilippoBonazziSUSE** [comment]
@denisok is that the right link? What are you referring to?

**Comment by denisok** [comment]
I mean not everyone use KeyPass and etc. make sense to have config for apps that we install, or some general one ppl will install.
