### ISSUE TITLE
Gentle suggestions: Swaylock-fancy

### ISSUE THREAD

**Issue by taschenlampe** [openSUSE/openSUSEway#39]
Hi!

First of all: I really like openSUSEway's look and feel, it's really great. Chapeau!

May I suggest that in a future release you may want to consider adding swaylock with some [swaylock-effects](https://github.com/mortie/swaylock-effects)? I think this would make oSw even nicer.

An other nice option would be to add a `"on-click-right": "exec alacritty -e nmtui-connect"` for the network-module  in waybar. This would be a quite handy little tool/shortcut...for laptop users.

**Comment by denisok** [comment]
Hi @taschenlampe,

thanks for the feedback, I will check it out!

Thanks,
Denys

**Comment by jubalh** [comment]
Make sense.
