### ISSUE TITLE
wofi

### ISSUE THREAD

**Issue by denisok** [openSUSE/openSUSEway#4]
- [x] package
- [x] branding
- [x] run/drun and etc
- [x] submit to Factory

https://build.opensuse.org/package/show/X11:Wayland/wofi

**Comment by denisok** [comment]
https://build.opensuse.org/request/show/798987

I need to update the package to use service files (as Source URL wouldn't work).
See discussion under:
https://build.opensuse.org/package/show/X11:Wayland/wofi

**Comment by jubalh** [comment]
Maybe you can paste the discussion here in case the comments get deleted in the future.

**Comment by denisok** [comment]
dkondratenko wrote about 1 month ago

@jengelh are you going to submit it to the Factory ? or should I?

Jan Engelhardt's avatar

jengelh wrote about 1 month ago

Feel free.

I'd like to know if you are ok with using Source URLs (now that I've shown on two packages how to make use of it) for the other 4-or-so pending packages.

Denis Kondratenko's avatar

dkondratenko wrote about 1 month ago

I am fine, so for wofi you just renamed the package? If so I will do that in the future.

Jan Engelhardt's avatar

jengelh wrote about 1 month ago

The package was not renamed. The tarball has the same name in OBS as it has on github (v1.1.2.tar.gz; last part of the URI). If you don't need to deviate, don't, it'll be simpler :-D

Denis Kondratenko's avatar

dkondratenko wrote about 1 month ago

I don't have any packages pending....

Jan Engelhardt's avatar

jengelh wrote about 1 month ago

795864 795863 795862; looks like jubalh set them to declined a few hours ago.

Denis Kondratenko's avatar

dkondratenko wrote about 1 month ago

That is a different person.

Denis Kondratenko's avatar

dkondratenko wrote about 1 month ago

Output of check script: v1.1.2.tar.gz /home/go/co/798987/wofi/v1.1.2.tar.gz differ: char 19, line 1 ERROR: download_files is configured to fail when the upstream file is different than the committed file... this is the case! Source URLs are not valid. Try "osc service localrun download_files

Jan Engelhardt's avatar

jengelh wrote about 1 month ago

Great. Their web service (looks a like cgit, but is something for hg‽) can't even produce a reproducible archive. Every download gives you a unique tarball. That sucks.

» diff -dpru <(hexdump -C vOLD) <(hexdump -C v1.1.2.tar.gz )
--- /dev/fd/63  2020-04-29 19:55:40.683843592 +0200
+++ /dev/fd/62  2020-04-29 19:55:40.683843592 +0200
@@ -1,6 +1,6 @@
 00000000  1f 8b 08 08 a0 27 67 5e  02 ff 76 31 2e 31 2e 32  |.....'g^..v1.1.2|
-00000010  62 27 34 66 32 64 31 36  64 61 30 36 34 36 62 32  |b'4f2d16da0646b2|
-00000020  65 62 27 2e 74 61 72 00  ec bd eb 7a db 48 92 28  |eb'.tar....z.H.(|
+00000010  62 27 61 30 66 37 35 30  66 65 65 61 65 35 62 38  |b'a0f750feeae5b8|
+00000020  34 34 27 2e 74 61 72 00  ec bd eb 7a db 48 92 28  |44'.tar....z.H.(|
 00000030  d8 7f 0b 4f 81 a3 de 6f  2c d5 47 d1 a2 64 cb ae  |...O...o,.G..d..|
 00000040  72 77 9f 91 25 da e6 94  2c 69 28 a9 dc ee e9 b3  |rw..%...,i(.....|
 00000050  5a 90 00 49 94 40 80 8d  8b 64 d6 ec 9c d7 38 cf  |Z..I.@...d....8.|

» file vOLD
vOLD: gzip compressed data, was "v1.1.2b'4f2d16da0646b2eb'.tar", last modified: Tue Mar 10 05:37:36 2020, max compression, original size modulo 2^32 327680
» file v1.1.2.tar.gz 
v1.1.2.tar.gz: gzip compressed data, was "v1.1.2b'a0f750feeae5b844'.tar", last modified: Tue Mar 10 05:37:36 2020, max compression, original size modulo 2^32 327680

Arnav Singh's avatar

Arnavion wrote 9 days ago

For future readers, the discussion of the repo host's issue is at https://lists.sr.ht/~sircmpwn/sr.ht-discuss/%3Caf46b926-510e-c337-7cb0-eb12df47ac88%40gmail.com%3E and https://todo.sr.ht/~sircmpwn/hg.sr.ht/33

Jan Engelhardt's avatar

jengelh wrote 9 days ago

If they have no stable source ball, then using a _service file on the openSUSE side is a legit solution.

**Comment by denisok** [comment]
https://build.opensuse.org/request/show/811556

**Comment by denisok** [comment]
submitted to Factory: https://build.opensuse.org/request/show/811664

**Comment by denisok** [comment]
SR accepted
