### ISSUE TITLE
An other suggestion: Update indicator (waybar)

### ISSUE THREAD

**Issue by taschenlampe** [openSUSE/openSUSEway#40]
Hi!
This may be just a personal wish, not sure if anyone else wants this: May I suggest to include an update widget to waybar . I have something like this:

```
  "custom/zypper": {
        "format": "{} ",
        "interval": 3600,
        "exec": "zypper lu | grep 'v |' | wc -l",
        "exec-if": "exit 0",
        "on-click": "exec alacritty -e sudo  zypper update ; pkill -SIGRTMIN+8 waybar",
        "signal": 8
    }
```
I must confess that I copied -and slighty adapted- the code from waybar's wiki...I am not 100% about this SIGTMIN+signal function...but heyho, it seems to do what it should do.

Cheers

**Comment by denisok** [comment]
ha, cool suggestion!. `zypper dup` probably and I will check about the signal.
waybar needs some love for sure, on my AMD laptop temps don't work as well.

Thanks! BTW there will be openSUSE conference, I have submitted a talk about openSUSEway, if you would like to participate - would be awesome :) maybe some feedback during the talk.

**Comment by taschenlampe** [comment]
Hi!
Sure thing, I'd like to listen to your talk. Though I cannot guarantee that my feedback (if I gave any ) , will make a lot of sense though :-D

**Comment by taschenlampe** [comment]
Using
`"exec": "zypper lu -a | grep 'v |    ' | wc -l"`
could be an option too (though there is some [issues](https://forums.opensuse.org/showthread.php/553134-Help-me-understand-Difference-between-output-of-zypper-dup-and-zypper-lu-a?highlight=zypper+lu+-a) with it, when you have several repos proposing the same packages. For me this is fine as I know (mas o menos) why I cannot upate all listed pakages) 
An other issue is, that after updating the system waybar will wait  (up to) 3600s until it refreshes the zypper/widget status...somehow the widget should reload itself after executing the command. I am not sure how to deal with it.

As I prefer  to update only when a new release is available I wrote this little script to check if a new release is available:

```
   "custom/release": {
        "format": "{} ",
        "exec" : "/usr/bin/sh /home/me/test.sh",
        "interval": 3600,
        "exec-if": "exit 0",
        "on-click": "exec alacritty -e sudo  zypper update ; pkill -SIGRTMIN+8 waybar",
        "signal": 8
    },
```
test.sh -> https://paste2.org/tADAWNbs

Please note: I am not a coder, I guess this script will make people laugh that actually know how to code :-D
