### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mcepl** [openSUSE/openSUSEway#51]
I had to restore one computer from backups and I was reminded again how far 0.13 is from our `master`. Could we get a new release?

**Comment by denisok** [comment]
sure, why not. I actually see some issue with greetd/gtkgreet not starting, maybe I hit #33 . Let me debug it for the few days and make release. You could submit one yourself as well, if you wish it faster.

**Comment by denisok** [comment]
done:
https://github.com/openSUSE/openSUSEway/releases/tag/0.14
https://build.opensuse.org/request/show/928865
