### ISSUE TITLE
greeter couldn't start the session

### ISSUE THREAD

**Issue by denisok** [openSUSE/openSUSEway#52]
In #33 @mcepl has an issue with greeter not starting:

```
May 24 12:59:15 stitny greetd[2497]: error: check_children: greeter exited without creating a session
```

since sometime I also started to have this issue.

I tried tuigreet. And that at least starts but something kills it before I could enter login and password, if I am really quick - I could login.
So probably same happens with gtkgreet, but that just takes more time to start and got killed faster even before showing something.

**Comment by mcepl** [comment]
Thank you.

**Comment by denisok** [comment]
@mcepl do you have GDM installed or `/usr/lib/systemd/logind.conf.d/reserveVT.conf` ?

In my case it was it, vt 1 was busy and we explicitly specify `vt = 1` in config file by default. could you try proposed patch and check if it works for you.

**Comment by mcepl** [comment]
I have GDM installed (that's the only loging manager which actually works for me) and
```
~@stitny$ cat /usr/lib/systemd/logind.conf.d/reserveVT.conf
[Login]
ReserveVT=1
~@stitny$
````

**Comment by denisok** [comment]
cool. @mcepl could you try the fix?

**Comment by mcepl** [comment]
see the comment in the pull request.
