### ISSUE TITLE
Update issue sway 1.7

### ISSUE THREAD

**Issue by taschenlampe** [openSUSE/openSUSEway#54]
Hi!

I found following message from zypper this morning: (I guess I dont need to translate this into english)

```
Problem: das zu installierende sway-1.7-1.1.x86_64 erfordert 'sway-branding = 1.7', aber diese Anforderung kann nicht bereitgestellt werden
  Nicht installierbare Anbieter: sway-branding-upstream-1.7-1.1.noarch[download.opensuse.org-oss]
                   sway-branding-upstream-1.7-1.1.noarch[openSUSE-20211025-0]
 Lösung 1: Folgende Aktionen werden ausgeführt:
  Deinstallation von sway-branding-openSUSE-0.14-1.3.noarch
  Deinstallation von openSUSEway-0.14-1.3.noarch
  Deinstallation von patterns-openSUSEway-0.14-1.3.noarch
 Lösung 2: veraltetes sway-1.6.1-3.3.x86_64 beibehalten
 Lösung 3: sway-1.7-1.1.x86_64 durch Ignorieren einiger Abhängigkeiten brechen
```

How should I proceed as Option 1 would nuke openSWAY

```
Die folgenden 19 NEUEN Pakete werden installiert:
  libruby3_1-3_1 libSPIRV-Tools-suse24 libwlroots10 ruby3.1
  ruby3.1-rubygem-abstract_method ruby3.1-rubygem-cfa ruby3.1-rubygem-cfa_grub2
  ruby3.1-rubygem-cheetah ruby3.1-rubygem-fast_gettext ruby3.1-rubygem-gem2rpm
  ruby3.1-rubygem-nokogiri ruby3.1-rubygem-ruby-augeas ruby3.1-rubygem-ruby-dbus
  ruby3.1-rubygem-simpleidn ruby3.1-rubygem-unf ruby3.1-rubygem-unf_ext swaybar
  sway-branding-upstream swaynag

Die folgenden 33 Pakete werden GELÖSCHT:
  libruby2_7-2_7 libruby3_0-3_0 libSPIRV-Tools-suse23 libwlroots9 openSUSEway
  patterns-openSUSEway ruby2.7 ruby2.7-rubygem-abstract_method ruby2.7-rubygem-cfa
  ruby2.7-rubygem-cfa_grub2 ruby2.7-rubygem-cheetah ruby2.7-rubygem-fast_gettext
  ruby2.7-rubygem-gem2rpm ruby2.7-rubygem-nokogiri ruby2.7-rubygem-ruby-augeas
  ruby2.7-rubygem-ruby-dbus ruby2.7-rubygem-simpleidn ruby2.7-rubygem-unf
  ruby2.7-rubygem-unf_ext ruby3.0 ruby3.0-rubygem-abstract_method
  ruby3.0-rubygem-cfa ruby3.0-rubygem-cfa_grub2 ruby3.0-rubygem-cheetah
  ruby3.0-rubygem-fast_gettext ruby3.0-rubygem-gem2rpm ruby3.0-rubygem-nokogiri
  ruby3.0-rubygem-ruby-augeas ruby3.0-rubygem-ruby-dbus ruby3.0-rubygem-simpleidn
  ruby3.0-rubygem-unf ruby3.0-rubygem-unf_ext sway-branding-openSUSE

Das folgende Schema wird GELÖSCHT:
  openSUSEway
```

Of course removing openSUSEway is clearly not an option :-D

**Comment by jubalh** [comment]
You should choose ` Lösung 3: sway-1.7-1.1.x86_64 durch Ignorieren einiger Abhängigkeiten brechen`.

It's caused by `Requires:       %{name}-branding = %{version}`.

@denisok  how should we handle this? Do you want to bump the branding package each time an update is done? Or should we put a <= 1.6 there and update manually each time? Remove the version thing?
Nothing sounds perfect :)

**Comment by denisok** [comment]
hm, I don't remmeber now how did it work, but I think this was added there: `%define sway_version %(rpm -q --queryformat "%%{version}" sway)` for that reason.

Maybe we should do `Provides:       sway-branding = %{sway_version}` . But interesting how did it work before. Because there is a same thing for the waybar, and that was updated number of times.

Need to investigate and refresh my memory about branding packages.

**Comment by mcepl** [comment]
I am not sure whether it is exactly sway’s problem, but with the latest updates I got even greetd broken:

![IMG_20220201_222718](https://user-images.githubusercontent.com/198999/152215734-1b0b0c46-48e6-4c12-945d-36bc8d5fa43a.jpg)

Unfortunately, I don’t have other debugging information than that I am using:
 * greetd-0.8.0-2.1.x86_64
 * openSUSEway-0.14-1.3.noarch
 * sway-1.7-1.1.x86_64
 * wlgreet-0.3-3.2.x86_64

**Comment by denisok** [comment]
@mcepl is that reproducible ? could you change service file and add that `RUST_BACKTRACE`? I am going to update and see :)

**Comment by mcepl** [comment]
> @mcepl is that reproducible ? could you change service file and add that `RUST_BACKTRACE`? I am going to update and see :)

Sorry, I am too tired and with had too much somewhere else. Where exactly should I put and what?

**Comment by denisok** [comment]
@jubalh  so the issue is after these changes:
https://build.opensuse.org/package/rdiff/X11:Wayland/sway?linkrev=base&rev=109#n50
https://build.opensuse.org/request/show/949422

that actually added dependency on the version. it wasn't there before. I don't know why that change was made

**Comment by denisok** [comment]
> > @mcepl is that reproducible ? could you change service file and add that `RUST_BACKTRACE`? I am going to update and see :)
> 
> Sorry, I am too tired and with my mind too much somewhere else. Where exactly should I put it and what?
in `/usr/lib/systemd/system/greetd.service` in `[Service]` section
```
Environment="RUST_BACKTRACE=1"
```

**Comment by jubalh** [comment]
> @jubalh so the issue is after these changes: https://build.opensuse.org/package/rdiff/X11:Wayland/sway?linkrev=base&rev=109#n50 https://build.opensuse.org/request/show/949422
> 
> that actually added dependency on the version. it wasn't there before. I don't know why that change was made

Oh!
I even asked the contributor about this whole block in: https://build.opensuse.org/request/show/948519
He mentioned rpmlint suggested this. My bad!

I can remove the version part tomorrow!

**Comment by denisok** [comment]
> > @jubalh so the issue is after these changes: https://build.opensuse.org/package/rdiff/X11:Wayland/sway?linkrev=base&rev=109#n50 https://build.opensuse.org/request/show/949422
> > that actually added dependency on the version. it wasn't there before. I don't know why that change was made
> 
> Oh! I even asked the contributor about this whole block in: https://build.opensuse.org/request/show/948519 He mentioned rpmlint suggested this. My bad!
> 
> I can remove the version part tomorrow!

https://build.opensuse.org/request/show/950825

done :)

**Comment by denisok** [comment]
> > @jubalh so the issue is after these changes: https://build.opensuse.org/package/rdiff/X11:Wayland/sway?linkrev=base&rev=109#n50 https://build.opensuse.org/request/show/949422
> > that actually added dependency on the version. it wasn't there before. I don't know why that change was made
> 
> Oh! I even asked the contributor about this whole block in: https://build.opensuse.org/request/show/948519 He mentioned rpmlint suggested this. My bad!

Interesting.

it might be deprecated, but wiki still says it is not: 
https://en.opensuse.org/openSUSE:Packaging_Branding

I tried to specify specific version (as 1.7) but it doesn't work. There should be additional magic then. But if it is deprecated - why it works? :) Probably I tried to fix those warning in the past, that why I have `sway_version` macro, but I failed.

I tried once again now, but it is also fails, even if I specify 1.7 version. It couldn't satisfy the dependency.

**Comment by Arnavion** [comment]
I have no opinion either way on what the specfile should say. The RPM lint suggested it, and the packages worked for me with its suggestions (I don't use openSUSEway or greetd, just sway and sway-branding-upstream directly), so I didn't know there was a problem. Thanks for fixing it.

**Comment by denisok** [comment]
> I have no opinion either way on what the specfile should say. The RPM lint suggested it, and the packages worked for me with its suggestions (I don't use openSUSEway or greetd, just sway and sway-branding-upstream directly), so I didn't know there was a problem. Thanks for fixing it.

no problem, you did well to try to fix it. Thanks for feedback and approval.

**Comment by mcepl** [comment]
![IMG_20220203_023159](https://user-images.githubusercontent.com/198999/152267485-4ab337bd-5cc5-435e-84e7-7b94720e0055.jpg)

This is probably the best what I can find.

**Comment by FilippoBonazziSUSE** [comment]
Is this still relevant?

**Comment by mcepl** [comment]
Let’s kill it for now.

**Comment by taschenlampe** [comment]
Yes, this can be closed.
