### ISSUE TITLE
Switch from mako to SwayNotificationCenter

### ISSUE THREAD

**Issue by danyspin97** [openSUSE/openSUSEway#62]
[SwayNotificaitonCenter](https://github.com/ErikReider/SwayNotificationCenter) is more user-friendly than mako and provides a toggable bar with all the unread messages. I think it would be a good addition to openSUSEway. A button can be added in waybar to toggle this panel.

**Comment by taschenlampe** [comment]
Hi!
This might not be the correct place to ask, but since @danyspin97  mentioned  SwayNC, I tried to install it, but I got stuck here:

```
ninja -C build       Mi 08 Jun 2022 11:34:53 CEST
ninja: Entering directory `build'
[1/18] Compiling Vala source ../src/client.vala src/constants.vala
FAILED: src/swaync-client.p/client.c src/swaync-client.p/constants.c
valac -C --debug --debug --enable-gobject-tracing --enable-checking -D WANT_SCRIPTING -D HAVE_LATEST_LIBHANDY -D HAVE_LATEST_GTK_LAYER_SHELL --pkg libhandy-1 --pkg json-glib-1.0 --pkg gtk+-3.0 --pkg gio-unix-2.0 --pkg gio-2.0 --color=always --directory src/swaync-client.p --basedir ../src --target-glib=2.50 --pkg=GtkLayerShell-0.1 ../src/client.vala src/constants.vala
error: Package `xlib-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GObject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `Gio-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `cairo-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GModule-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `Gio-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GObject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `cairo-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GObject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 9 error(s), 0 warning(s)
```
Any ideas how to get rid of these errors? 
Peace!

**Comment by danyspin97** [comment]
Hi @taschenlampe, you can try my WIP package in my home project:

https://build.opensuse.org/package/show/home:dspinella/SwayNotificationCenter

**Comment by mcepl** [comment]
Seems to work well, looks more readable than mako.

**Comment by denisok** [comment]
cool. Lets replace mako with it. I submitted package to X11:Wayland and lets push it to Factory to add to the openSUSEway

**Comment by denisok** [comment]
CC @jubalh https://build.opensuse.org/request/show/988089 please check and accept :)

**Comment by jubalh** [comment]
> CC @jubalh https://build.opensuse.org/request/show/988089 please check and accept :)

Done :)

**Comment by denisok** [comment]
@danyspin97 build failed for i586: https://build.opensuse.org/package/show/X11:Wayland/SwayNotificationCenter
check it out please. After it fixed - we can push to Factory.

**Comment by danyspin97** [comment]
Hi @denisok, it was an issue with the workaround I added in the spec file for the systemd service and now the i586 build has been fixed.

**Comment by FilippoBonazziSUSE** [comment]
Hi, I've submitted SwayNotificationCenter v0.6.3 to X11:Wayland: https://build.opensuse.org/request/show/988762

I've also added a `_service` file which hopefully will be useful to submit future versions

**Comment by denisok** [comment]
@FilippoBonazziSUSE thanks for update, btw I see `obscpio ` and `tar.gz` I thought it is either one or another. As I remember `obscpio ` is just better format to be stored inside obs. So maybe we don't need `tar.gz` there? But I am not sure. @jubalh is much more experienced package maintainer.

**Comment by jubalh** [comment]
>  As I remember obscpio is just better format to be stored inside obs. So maybe we don't need tar.gz there?

That's right AFAIK.
https://build.opensuse.org/request/show/988917

**Comment by denisok** [comment]
@FilippoBonazziSUSE I think this is done :) should be closed? At least for the new user :)

**Comment by FilippoBonazziSUSE** [comment]
I agree, the default for new users is now SwayNotificationCenter. I feel like we should still remove `mako` as a hard requirement, but I'm not sure how to achieve that. However that's tracked in #103, so this can be closed
