### ISSUE TITLE
Trying to change default shell to fish

### ISSUE THREAD

**Issue by yoogui** [openSUSE/openSUSEway#64]
Hi all.
I'm trying to change the default shell to fish, but when I do that, sway doesn't start from login manager (sddm in my case). Plasma starts well. If I revert the default shell to bash, sway boots from sddm without problem. 

I don't know if the problem is maybe de .sh wrapper file invoked from de sway.desktop or anything else.

Can you help me with this issue?
Thanks.

**Comment by mcepl** [comment]
Don’t setup fish as a shell for root, because (quoting its help): “Fish is intentionally not POSIX-compatible and as such some of the things you are used to work differently.”, so whenever any script has a shebang `#!/bin/sh` (which is almost all of them) it fails.

**Comment by yoogui** [comment]
Thank for the advice. I read the fish documentation and other articles related to login and interactive shells, and I decide to leave fish as a interactive shell for commands and navigating purposes. Still leave bash as a default login shell.
