### ISSUE TITLE
fontawesome

### ISSUE THREAD

**Issue by bobblkabb** [openSUSE/openSUSEway#65]
Installed Leap with "minimal installation" to add openSUSEway via the pattern file. This file should include fontawesome because of the waybar icons.

**Comment by denisok** [comment]
Hi @bobblkabb, thanks for reporting. I actually see that package in the pattern:
```
Requires:       sway-branding-openSUSE
```

and `sway-branding-openSUSE` includes it:
```
Requires:       fontawesome-fonts
```

I think Leap doesn't have openSUSEway pattern, does it ? How did you install openSUSEway on Leap?

maybe you used `patterns-sway`? : https://build.opensuse.org/package/view_file/X11:Wayland/patterns-sway/patterns-sway.spec?expand=1

that doesn't have fontawesome, and I agree it needs to be added:
https://build.opensuse.org/request/show/988092

Thanks,
Denys

**Comment by denisok** [comment]
done
