### ISSUE TITLE
Some missing utilities which could be included

### ISSUE THREAD

**Issue by mcepl** [openSUSE/openSUSEway#74]
When discussing https://www.reddit.com/r/openSUSE/comments/w92o0w/comment/ihtrne4/?context=3 I have just checked that we are including in our default sets of packages everything which normal user of sway can use. I have checked packages which I use and which are not included in openSUSEway and sway patterns:

 * [ ] clipman
 * [ ] mpris-ctl
 * [ ] sway-marker
 * [ ] wl-clipboard

Do we have all included in our standard sets? Is there something else we are missing?

**Comment by jubalh** [comment]
Update: All 4 packages are available in Factory.

**Comment by denisok** [comment]
adding them, as part of 0.15-rc .

BTW @mcepl you always could submit package update.

@jubalh I am thinking to add openSUSEway.spec to the repo as well. I know it is kinda dup for the OBS, but actually when adding new stuff it could be handy - so if there is new dependency required - you could add it as part of a PR into the spec file.,

**Comment by denisok** [comment]
@mcepl I see we have `clipman` as part of the spec, is that the same as `wl-clipboard` or different?

**Comment by mcepl** [comment]
> @mcepl I see we have `clipman` as part of the spec, is that the same as `wl-clipboard` or different?

stitny~$ rpm -qf /usr/bin/clipman
clipman-1.6.1-1.6.x86_64
stitny~$ rpm -qf /usr/bin/wl-*
wl-clipboard-2.1.0-1.4.x86_64
wl-clipboard-2.1.0-1.4.x86_64
stitny~$ 

https://github.com/yory8/clipman

**Comment by denisok** [comment]
added in #91

**Comment by jubalh** [comment]
> @jubalh I am thinking to add openSUSEway.spec to the repo as well. I know it is kinda dup for the OBS, but actually when adding new stuff it could be handy - so if there is new dependency required - you could add it as part of a PR into the spec file.,

Yes it makes sense. Makes it easier to track the changes immediately and also for debugging purposes/see when something got added.

**Comment by FilippoBonazziSUSE** [comment]
How would you handle the OBS update then? `osc service manualrun` to fetch the new release, then extract and copy out the new spec file?

**Comment by FilippoBonazziSUSE** [comment]
We could also add this sort of out-of-band mechanism:

Add a download_url source service that downloads the spec file from the Github URL
https://github.com/openSUSE/obs-service-download_url/blob/master/download_url.service

**Comment by FilippoBonazziSUSE** [comment]
Follow-up suggestion: the `obs-service-extract_file` service seems to be exactly what we're looking for.

https://github.com/openSUSE/obs-service-extract_file

**Comment by denisok** [comment]
there also was a project - to use git as a storage: https://events.opensuse.org/conferences/oSC22/program/proposals/3905

but extracting file from the tarball looks as a good solution - Thanks!

Lets integrate that
