### ISSUE TITLE
Add rofi styling

### ISSUE THREAD

**Issue by mcepl** [openSUSE/openSUSEway#75]
Yes, I understand that we prefer [wofi](https://hg.sr.ht/~scoopta/wofi) for our menu application system (although, that seems to be abandoned), but [rofi](https://build.opensuse.org/package/show/home:mcepl:work/rofi-wayland) seems to be much more capable, so there are applications based on it (e.g., I use [pinentry-rofi](https://build.opensuse.org/package/show/home:mcepl:work/pinentry-rofi)), which cannot be reasonably ported to wofi. And yes, I have pointed out to the rofi port to Wayland.

Unfortunately the problem is that whenever I run any rofi-based application it looks like an alien on my openSUSEway desktop:

![screenshot-2022-08-26_18-08-1661532787](https://user-images.githubusercontent.com/198999/186954561-abffaa09-809b-49a6-a3b5-d3636ec3e8d9.png)

(and that's my attempt to find the least offensive rofi theming)

This ticket should consolidate all effort to create some kind of theme for rofi, so that it wouldn't look so horrible.

* Arch Wiki (as usual) has a lot to say on [Rofi](https://wiki.archlinux.org/title/Rofi)

**Comment by uncomfyhalomacro** [comment]
Why not Fuzzel?

**Comment by jubalh** [comment]
Could you post a comparison? We have both in repos.

**Comment by uncomfyhalomacro** [comment]
**Fuzzel**

Fuzzel can now be configured in `ini` file-format. It's simple to use and can be configured with [`tessen`](https://github.com/ayushnix/tessen), a script to interact [`pass`](https://www.passwordstore.org/).

It can also be configured with [`fnott`](https://codeberg.org/dnkl/fnott) as well since fnott can now be also configured with `ini` file-format. With a keybind to run a script, one can finally interact notifications using fuzzel.

```sh
#!/bin/bash

shopt -s lastpipe

if [ "$1" == "act" ]
then
    fnottctl list | fuzzel -p \
        "Select notif to act on: " \
        -s f2d26fff \
        -S 173f4fff \
        -t 35b9abff \
        -b 061C2Aff \
        -r 0 \
        -C 81c13bff \
        -f "JetBrains Mono:size=8" \
        -x 30 \
        -w 45 \
        -y 70 \
        -l 20 \
        --dmenu \
        --no-run-if-empty | read -r notif

    fnottctl actions "$(echo "${notif}" | cut -d':' -f1)"
else
    fnottctl list | fuzzel -p \
        "Select notif to dismiss: " \
        -s f2d26fff \
        -S 173f4fff \
        -t 35b9abff \
        -b 061C2Aff \
        -r 0 \
        -C 81c13bff \
        -f "JetBrains Mono:size=8" \
        -x 30 \
        -w 45 \
        -y 70 \
        -l 20 \
        --dmenu \
        --no-run-if-empty | read -r notif

    fnottctl dismiss "$(echo "${notif}" | cut -d':' -f1)"
fi

```

**Screenshots**

![image](https://user-images.githubusercontent.com/66054069/214078401-500901d3-0e3b-48bd-bd18-c8dba33f7974.png)

![image](https://user-images.githubusercontent.com/66054069/214078509-76d74d5e-c8db-4b06-9c88-45a2bfecda20.png)

![image](https://user-images.githubusercontent.com/66054069/214079049-6bdd36df-955b-4a4b-bbd5-037eb9fbf85d.png)

**Cons**
The only con I think is also it's pros. Fuzzel can be configured with ini but it cannot be configured *as complex as those like rofi's or wofi's*. However, it does the job well, and it requires little configuration so I think it's a win for me.

**Comment by mcepl** [comment]
> Why not [fuzzel](https://codeberg.org/dnkl/fuzzel)

Because rofi is much more than just `drun` substitute. See for example https://github.com/plattfot/pinentry-rofi (aka https://build.opensuse.org/package/show/home:mcepl/pinentry-rofi).

With relation to images, see for example this regular wofi menu:

![Uploading screenshot-2023-01-23_16-01-1674489309.png…]()

with this pinentry-rofi:

![Uploading screenshot-2023-01-23_16-01-1674489517.png…]()

**Comment by uncomfyhalomacro** [comment]
> > Why not [fuzzel](https://codeberg.org/dnkl/fuzzel)
> 
> Because rofi is much more than just `drun` substitute. See for example https://github.com/plattfot/pinentry-rofi (aka https://build.opensuse.org/package/show/home:mcepl/pinentry-rofi).

Isn't pinentry rofi just a script that utilizes drun mode of rofi? I think that can be done with fuzzel since fuzzel also has drun mode.

I

**Comment by mcepl** [comment]
> Isn't pinentry rofi just a script that utilizes dmenu mode of rofi? I think that can be done with fuzzel since fuzzel also has dmenu mode.

Taken this way, there is no reason why not to use `wofi(1)`, which is already installed. Rewrite of `pinentry-rofi` either to some reasonable language (aka anything else than Scheme ;), OK, no Haskell either, please) or using wofi/fuzzel would be more than welcome.

**Comment by uncomfyhalomacro** [comment]
> Hmm, there is a reason, why not to use `wofi(1)`: it seems to be abandoned. If we want to continue depend on it, somebody should make a fork (or ask for co-maitaining it … it is not completely abandonded, last commit is 29 days ago), and at least collect all those patches.

It's possible someone can take over and maintain it given there are many users that do use it. I have no problem with wofi. Or maybe a rewrite for newer GTK versions inspired from it.

**Comment by mcepl** [comment]
> Taken this way, there is no reason why not to use `wofi(1)`, which is already installed. Rewrite of `pinentry-rofi` either to some reasonable language (aka anything else than Scheme ;), OK, no Haskell either, please) or using wofi/fuzzel would be more than welcome.

I have created such replacement as [pinentry-rofi](https://git.sr.ht/~mcepl/pinentry-rofi) which is pure bash, but otherwise I have left openSUSEway and do [Moldavite](https://sr.ht/~mcepl/moldavite/) instead … full MicroOS/Sway-based distro.

**Comment by denisok** [comment]
@mcepl congrats on it! I will put alternatives to README! yours and https://github.com/ProjectGreybeard/Info

**Comment by FilippoBonazziSUSE** [comment]
Should we consider a wofi alternative then?

**Comment by uncomfyhalomacro** [comment]
Seems wofi is maintained again! https://sr.ht/~scoopta/wofi/

**Comment by mcepl** [comment]
> Seems wofi is maintained again! https://sr.ht/~scoopta/wofi/

Yes, but rofi is much more capable and wofi doesn’t provide anything like the wealth of scripts like https://github.com/davatorium/rofi/wiki/User-scripts.

**Comment by FilippoBonazziSUSE** [comment]
> Seems wofi is maintained again! https://sr.ht/~scoopta/wofi/

There is still this banner though... I don't know

![image](https://github.com/openSUSE/openSUSEway/assets/101266837/3f44ab5f-061c-49d0-ae43-3fcd9eb68b8b)

**Comment by mcepl** [comment]
> > Seems wofi is maintained again! https://sr.ht/~scoopta/wofi/
> 
> There is still this banner though... I don't know

Run <Ctrl-Shift-R>. I have there just “Wofi is a launcher/menu program for wlroots based wayland compositors such as sway”.

**Comment by mcepl** [comment]
Well, [the last patch](https://lists.sr.ht/~scoopta/wofi/patches/43447) has been applied 5 months ago, but is it truly dead?
