### ISSUE TITLE
screenshots for openSUSE Leap 15.2

### ISSUE THREAD

**Issue by denisok** [openSUSE/openSUSEway#8]
Lubos asked me to add couple of screenshots, so I did.

https://progress.opensuse.org/issues/61410
https://en.opensuse.org/Portal:15.2/Screenshots#Sway_1.4

**Comment by denisok** [comment]
done, if someone have better screenshots - they could be added.

**Comment by jubalh** [comment]
First time I see the openSUSE branding. Looks great!

**Comment by denisok** [comment]
@jubalh I need to progress to get it to Factory...
