### ISSUE TITLE
Issue while updating

### ISSUE THREAD

**Issue by taschenlampe** [openSUSE/openSUSEway#85]
Hi!

What would you suggest I should do

![Screenshot_20221203_154110](https://user-images.githubusercontent.com/10836480/205446526-1feb08b8-5fc1-4df2-b404-ecdaf82d68c3.png)

**Comment by jubalh** [comment]
https://bugzilla.suse.com/show_bug.cgi?id=1205950

**Comment by taschenlampe** [comment]
Thanks for the information & link.

**Comment by FilippoBonazziSUSE** [comment]
Fix submitted in [SR#1040414](https://build.opensuse.org/request/show/1040414). Sorry for the inconvenience.

Since this is not an openSUSEway problem this issue can be closed.
