### ISSUE TITLE
waysay

### ISSUE THREAD

**Issue by jubalh** [openSUSE/openSUSEway#9]
Might be of interest once it has a release: Native wayland desktop notifications https://github.com/JoshMcguigan/waysay

**Comment by m-rey** [comment]
Why should `waysay` be used here, if `swaynag` is already available and even the documentation on https://github.com/JoshMcguigan/waysay#waysay-vs-swaynag states that ```Most users will be better off using swaynag```?

**Comment by jubalh** [comment]
It don't get your question. This issue is about packaging waysay, so we don't forget about it. We also package waybar even though we already have a bar. Why shouldn't we package waysay?

**Comment by m-rey** [comment]
It wasn't clear to me that this issue was created as a reminder to package `waysay` once it has a release.
Packaging it is of course a good thing!

**Comment by jubalh** [comment]
waysay didn't have any commits since 2 years and no releases.
I think we can close this.
