### ISSUE TITLE
Release 0.15 on OBS does not contain all changes from GH release 0.15

### ISSUE THREAD

**Issue by FilippoBonazziSUSE** [openSUSE/openSUSEway#99]
Hi, I just noticed that the current 0.15 release tarball on OBS does not contain all changes from the 0.15 tagged release on Github. At least `.config/alacritty/alacritty.yml` is different (still contains old content), possibly other files as well. I'm not sure how this happened.

I'm going to fix this by submitting a SR on OBS adding a _service file which uses the `obs_scm` service. This way we can always be sure that we're pulling all GH changes.

**Comment by FilippoBonazziSUSE** [comment]
Fix submitted in https://build.opensuse.org/request/show/1062433

**Comment by jubalh** [comment]
https://build.opensuse.org/request/show/1062433 accepted

**Comment by FilippoBonazziSUSE** [comment]
I checked again and now the same OBS tarball is fine. What the hell did I see the first time around?? I'm sure I saw the outdated alacritty config, as I still had the visible warning in my terminal in a VM. Maybe the VM was not updated as I thought it was?

Anyway this change should be just a net improvement regardless.
